Update requirements_gpu.txt
The conflict is caused by:
    The user requested numpy==1.20.0
    imageio 2.13.3 depends on numpy
    imgaug 0.4.0 depends on numpy>=1.15
    matplotlib 3.5.1 depends on numpy>=1.17
    opencv-python 4.5.4.60 depends on numpy>=1.21.2

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict

ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts